import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst } from 'workbox-strategies';

// 1. Precache static assets (JS, CSS, Images generated by build)
precacheAndRoute(self.__WB_MANIFEST);

// 2. Runtime Caching for Navigation (HTML)
// We use a direct match function to ensure we capture the SSR HTML responses.
registerRoute(
  // Match function: checks if the request is for a page navigation
  ({ request }) => request.mode === 'navigate',

  // Strategy: Network First
  // It tries to fetch the freshest HTML from the server.
  // If offline, it falls back to the version saved in 'pages-cache'.
  new NetworkFirst({
    cacheName: 'pages-cache',
    plugins: [
      // You can add plugins here if needed
    ]
  })
);

// Console log to verify in the browser that this specific version is running
console.log("Service Worker with pages-cache loaded successfully 🚀");