import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { NetworkFirst } from 'workbox-strategies';

// Precache all static assets generated by the build (CSS, JS, Images)
precacheAndRoute(self.__WB_MANIFEST);

// Handle navigation requests (HTML) with a Network First strategy
// This allows the app to work offline by caching the SSR responses
const navigationRoute = new NavigationRoute(
  new NetworkFirst({
    cacheName: 'pages-cache',
    plugins: [
      // You can add plugins here if needed (e.g., CacheableResponsePlugin)
    ]
  })
);

registerRoute(navigationRoute);