import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst } from 'workbox-strategies';
import { clientsClaim, skipWaiting } from 'workbox-core';

// 1. Immediate activation
// This ensures the SW takes control of the page immediately after installation,
// without waiting for a refresh.
skipWaiting();
clientsClaim();

// 2. Precache static assets (JS, CSS, Images generated by the build)
// @ts-ignore - __WB_MANIFEST is injected by Workbox at build time
precacheAndRoute(self.__WB_MANIFEST);

// 3. CACHE WARM-UP (Crucial for first-load offline support)
// This manually caches the root HTML page ('/') during the installation phase.
// This ensures that if a new user visits the site and immediately goes offline
// without refreshing, the app shell is already in the cache.
// @ts-ignore - Service Worker API types
self.addEventListener('install', (event) => {
	const urlsToCache = ['/'];
	// @ts-ignore - waitUntil is available on ExtendableEvent
	event.waitUntil(
		caches.open('pages-cache').then((cache) => {
			console.log('🔥 Cache warm-up: Caching initial HTML...');
			return cache.addAll(urlsToCache);
		})
	);
});

// 4. Runtime Caching for Navigation (HTML)
// Strategies: Network First.
// - Online: Fetches fresh HTML from the server and updates the cache.
// - Offline: Serves the HTML saved in 'pages-cache'.
registerRoute(
	({ request }) => request.mode === 'navigate',
	new NetworkFirst({
		cacheName: 'pages-cache',
		plugins: []
	})
);

console.log('Service Worker: Ready, warmed up, and controlling the page! 🚀');
